### PR TITLE
Gen object fix

### LINKED ISSUE #100: rpc json generator - include object param/return data
format:
```
"params": [{ "description": "...", "details": { "from": "...", ... } }]
```

blocks #67

### PR DESCRIPTION
**Pull request by goldylucks**
resolves #100 and #67

### CODE REVIEW

File: client/util/rpc-md.js [hunk 1]
```diff
@@ -0,0 +1,13 @@
+
+import { isPlainObject } from 'lodash';
+
+export function formatRpcMd (val) {
+  if (!isPlainObject(val)) {
+    return val;
+  }
+
+  return Object.keys(val.details).reduce((acc, key) => {
```
Comment (tomusdrw) [inline client/util/rpc-md.js]: .reduce -> .map(..).join('\n')
