### PR TITLE
handle rpc formatters exceptions

### LINKED ISSUE #35: In RPC we should catch possible exceptions from formatters

### PR DESCRIPTION
**Pull request by Adam-Goldman7**
resolves #35

### CODE REVIEW

File: client/provider/rpc-provider.js [hunk 1]
```diff
@@ -11,21 +11,29 @@ export default class RpcProvider {
...
     } else {
-      formatter = this._web3Formatters[formatter];
+      formatter = this._web3Formatters[formatterName];
+    }
+    try {
+      return `${formatter(result)}`;
+    } catch (err) {
+      const msg = `error using ${formatterName} on ${result}: ${err}`;
+      console.error(msg);
+      return new Error(msg);
```
Comment (tomusdrw) [inline client/provider/rpc-provider.js]: What about displaying error message?

Comment (Adam-Goldman7) [inline client/provider/rpc-provider.js]: in an error toast?

Comment (tomusdrw) [inline client/provider/rpc-provider.js]: :+1:
